# Generated by Django 3.0.2 on 2020-02-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('release_year', models.IntegerField()),
                ('transmission', models.IntegerField(choices=[(1, 'Mechanics'), (2, 'Automatic'), (3, 'Robot')])),
                ('color', models.CharField(max_length=25)),
            ],
        ),
    ]
